name: JFrog Xray Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  xray-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          chmod +x jfrog

      - name: Configure JFrog CLI
        env:
          JFROG_URL: ${{ secrets.JFROG_URL }}
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
        run: |
          ./jfrog config add my-server --url $JFROG_URL --user $JFROG_USERNAME --password $JFROG_PASSWORD --interactive=false

      - name: Run Xray Scan
        run: ./jfrog xr scan .
