name: Xray Scan

on:
  push:
    branches:
      - master

jobs:
  scan:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli-action@v1

      - name: Configure JFrog CLI
        run: jfrog rt c --url YOUR_ARTIFACTORY_URL --user ${{ secrets.JFROG_USER }} --password ${{ secrets.JFROG_PASSWORD }}

      - name: Run JFrog Xray scan
        run: jfrog rt xray <your-artifact-repo-name> --fail-fast --output json
